### ISSUE TITLE
 Windows desktop does not use starling to run ane will crash directly

### ISSUE THREAD

**Issue by gs600981** [tuarua/WebViewANE#149] opened 2018-05-14 09:50 UTC
- What version are you using?
1.6.1

- **On what operating system?**
    -  Win10
    
- **If Windows is it?**
    - 64bit

- **Which IDE are you using?**
    - Flash Builder

- **Which version of AIR are you using?**
    - AIR 29.0

 The sample runs without problems ,But Windows desktop does not use starling to run ane will crash directly

![image](https://user-images.githubusercontent.com/8640698/39991416-11e14e58-57a2-11e8-9fce-bd6919f32ad4.png)

**Comment by tuarua** [comment] 2018-05-14 18:34
Please see https://forum.starling-framework.org/topic/webviewane-for-osx/page/7?replies=201#post-105524
Duplicate of #60

**Comment by gs600981** [comment] 2018-05-15 01:18
thank

**Closed** 2018-05-15 18:36 UTC
Labels: duplicate
