### ISSUE TITLE
Error trying to run the ANE in Debug mode in Flash Builder 4.7

### ISSUE THREAD

**Issue by gdeverlant** [tuarua/WebViewANE#166] opened 2018-07-28 12:44 UTC
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
Version 1.8.0

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
Windows 7

- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit
64 Bits

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
FlashBuilder 4.7

- **Which version of AIR are you using?**
    - 29,30.. etc?
AIR 30

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
Demo file : [ChromeTest.zip](https://github.com/tuarua/WebViewANE/files/2237967/ChromeTest.zip)

- **What is the expected output? What do you see instead?**
Loading of the web site but i get this error

![error](https://user-images.githubusercontent.com/26530975/43356629-8a4e74f8-9274-11e8-912c-62290dfe59b4.png)

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

```

**Comment by gdeverlant** [comment] 2018-07-28 12:48
I followed the steps in : https://github.com/tuarua/WebViewANE/wiki/Chromium-WebView

C# library files Important!

Download cef_binaries_x86.zip from the latest release tag
Unzip the contents of cef_binaries_x86.zip into the bin folder of your AIRSDK.
Copy the contents of the c_sharp_libs_x86 folder into the bin folder of your AIRSDK.

+ I made sure that I'm running x86 files

AIR29 now includes 32bit and 64bit in the AIR SDK. However it appears adl.exe is 32bit only. Therefore when debugging use x86 version of the cef and cefsharp dlls.

**Comment by gdeverlant** [comment] 2018-07-28 13:03
Ok the problem is resolved with .NET installed.

Now I get this :

![error](https://user-images.githubusercontent.com/26530975/43356766-52f26ff2-9277-11e8-93f9-cfcb5818b6f7.png)

**Comment by gdeverlant** [comment] 2018-08-05 12:09
I updated everything like you mentioned and it still doesn't work.

This time I get an error from within the AIR app. There not much said about the error.

![error](https://user-images.githubusercontent.com/26530975/43685756-18b40a42-98b9-11e8-8643-ec2e9110fcea.png)

**Comment by tuarua** [comment] 2018-08-06 21:01
Already addressed:

here https://github.com/tuarua/WebViewANE/wiki/Troubleshooting---FAQs#adl-crashes-when-i-run-on-windows

and here https://github.com/tuarua/WebViewANE/issues/74
and here https://github.com/tuarua/WebViewANE/issues/154
and here https://github.com/tuarua/WebViewANE/issues/149
and here https://github.com/tuarua/WebViewANE/issues/46

**Comment by gdeverlant** [comment] 2018-08-08 21:17
I'm sorry but nothing there is helping me it is too vague.

I tried to make a release of my app as Captive Runtime and it doesn't work in debug mode.

**Comment by tuarua** [comment] 2018-08-12 11:17
Closing as duplicate.
Crash is caused by not following the instructions to copy the required dlls. See linked issues.

**Closed by tuarua** 2018-08-12 11:17 UTC
Labels: duplicate
