### ISSUE TITLE
Error from Animate CC 2018 - "undefined method CommonDependencies"

### ISSUE THREAD

**Issue by mc3dev** [tuarua/WebViewANE#178] opened 2018-09-07 19:54 UTC
Hi,

I am using Animate CC 2018 and ran into errors. I cannot find a sample code for Animate CC. Is it possible to provide sample code for Animate CC? Below are the errors and the fla file is attached. Thank you for your help!

Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
YES.
    
- **What version of the product are you using?**
    - What version are you using?
version 1.8.3

- **On what operating system?**
Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit

- **Which IDE are you using?**
    - Animate CC 2018

- **Which version of AIR are you using?**
    AIR 31

- **What steps will reproduce the problem?**
    - I've followed the wiki steps and added ANE + Dependencies for Chromium WebView. Contents of the c_sharp_libs_x86 folder have been added into the bin folder of AIRSDK. Added the WebViewANE.ane file in the fla file with the actionscript on frame 1 of the fla. When it ran it displayed the "undefined method of CommonDependencies" errors (see attached test.fla and errors below.)

- **What is the expected output? What do you see instead?**
Expected output - the test should run.

Instead it shows errors:
Scene 1, Layer 'Layer_1', Frame 1, Line 11, Column 28	1046: Type was not found or was not a compile-time constant: CommonDependencies.
Scene 1, Layer 'Layer_1', Frame 1, Line 1, Column 18	1172: Definition com.tuarua:CommonDependencies could not be found.
Scene 1, Layer 'Layer_1', Frame 1, Line 1, Column 18	1172: Definition com.tuarua:CommonDependencies could not be found.
Scene 1, Layer 'Layer_1', Frame 1, Line 11, Column 53	1180: Call to a possibly undefined method CommonDependencies.

- **Please provide any additional information below.**
    -"test.fla" is attached with code.
[test.zip](https://github.com/tuarua/WebViewANE/files/2362311/test.zip)

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**
Do not have the Animate CC version to test from.

**Comment by tuarua** [comment] 2018-09-07 20:33
Please see
https://github.com/tuarua/WebViewANE/issues/75#issuecomment-323971188

You can get the file at 
https://github.com/tuarua/Swift-IOS-ANE/releases/download/2.5.0/CommonDependencies.ane

or remove all references to it if you are only targeting Windows

**Comment by tuarua** [comment] 2018-09-10 21:49
Have you searched the issue tracker to see if others have had the same problem?
Have you re-read the wiki to check you have completed the setup correctly?
Have you read the troubleshooting / FAQs section?

Please follow these steps first.
If you prefer one-to-one help please contact info@tuarua.co.uk for paid support.

**Comment by mc3dev** [comment] 2018-09-18 20:56
I did but will check again to see what I missed. Thanks.

**Comment by mc3dev** [comment] 2018-09-18 21:41
I missed this "Copy the contents of the c_sharp_libs_x86 folder into the bin folder of your AIRSDK." \
After I have updated to the latest release following wiki's instructions, I can run the .fla in Animate in Test mode. However, when I published to "Windows Installer" (.exe) or published to "Application with Runtime Embedded" and run the exe inside the AIR package, neither of two launch the app (exe). Nothing happens. 

Can you please advice? Thank you.

**Comment by tuarua** [comment] 2018-09-19 18:46
It is mentioned clearly in the wiki that you also need to package the files when packaging a release.

See this existing ticket for Animate details.
https://github.com/tuarua/WebViewANE/issues/14#issuecomment-282433188

Closing as this is not a bug and duplicates existing issues in the tracker.

If you need any further help please contact info@tuarua.co.uk for paid support.

**Closed by tuarua** 2018-09-19 18:46 UTC
Labels: invalid
