### ISSUE TITLE
Webview not displayed

### ISSUE THREAD

**Issue by coxfrederic** [tuarua/WebViewANE#159] opened 2018-06-14 14:19 UTC
Answer the below. **DO NOT DELETE!!**

- **Have you read the README carefully?**
    - Follow the instructions provided before raising an issue.
  
Yes

- **What version of the product are you using?**
    - What version are you using?
e.g. 0.0.27

1.6.5

- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
    
Win7

- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit

32bit

- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?

Flash Builder

- **Which version of AIR are you using?**
    - 29,30.. etc?

20

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.

I call the following code:

`webView = new WebViewANE;
					var settings:Settings = new Settings;
					var thisL:Point = new Point(0,0);
					var thisG:Point = localToGlobal(thisL);
					var webViewViewport:Rectangle = new Rectangle(thisG.x + 5, thisG.y + 5, this.width - 30, this.height - 10);
					webView.init(stage, webViewViewport, "", settings, 1, 0xFFFFFF, false);
					webView.load("http://www.google.be");
this.callLater(showWebview);
}

private function showWebview():void{
				webView.visible = true;
			}

`

- **What is the expected output? What do you see instead?**

I expect to see the website http://www.google.be. Instead I am seeing nothing. Nothing is rendered on screen.

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

If I right click the screen where the webView is positioned then a context menu pops up and I can select "View source" (amongst other options like "Print"). When I click "View source" I can see the source for http://www.google.be.

So the website is loaded correctly but just not displaying.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

No

**Comment by coxfrederic** [comment] 2018-06-14 14:20
Same code works on Mac OSX.

**Comment by tuarua** [comment] 2018-06-16 10:45
I am not able to reproduce this.

**Comment by smorales** [comment] 2018-06-20 18:56
Shouldn't 
`var settings:Settings = new Settings;` 
be 
`var settings:Settings = new Settings();` ?

**Comment by coxfrederic** [comment] 2018-06-20 22:21
No that does not matter.

I tried with version 1.5.0 and the same issue ..
Which version of AIR is required for 1.5.0? I'm using AIR 20

**Comment by tuarua** [comment] 2018-07-03 21:35
Please respond to my question or I will close this issue in 7 days.

It's important to confirm existence of an issue with the reference before making guesses such as AIR version. This is standard practice in many projects.

**Comment by coxfrederic** [comment] 2018-07-06 13:10
I can not confirm this yet since I did not have the time to look into it. I found a workaround and due to a busy period both professionally and personally I'm not able to spend time on this issue.
If you feel you need to close the issue then you can do so.

**Closed** 2018-07-07 11:48 UTC
