### ISSUE TITLE
Resizing and bounds not showing correctly

### ISSUE THREAD

**Issue by gdeverlant** [tuarua/WebViewANE#230] opened 2019-10-10 18:16 UTC
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
   Yes
    
- **What version of the product are you using?**
    - What version are you using?
2.8.0

- **On what operating system?**
    Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    32bit

- **Which IDE are you using?**
    Flash Builder

- **Which version of AIR are you using?**
    31

- **What steps will reproduce the problem?**
    basic setup
- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

**WindowedApplication with Apache Flex 4.16.1 + AIR 31**

Ok it works well but unfortunately the resizing seems to be problematic.

![image](https://user-images.githubusercontent.com/26530975/66592710-e4099b00-eb95-11e9-8200-da9a48ae68a7.png)

In normal browser it is centered all

![image](https://user-images.githubusercontent.com/26530975/66592863-2b902700-eb96-11e9-97f0-bac0bbb6667f.png)

Any idea why it is cropped ?

**Comment by tuarua** [comment] 2019-10-11 10:08
Please confirm you can reproduce the problem with the reference flex example included with the repo.

**Comment by tuarua** [comment] 2019-10-18 11:24
Ticket will be closed in 7 days unless a response is received.

**Comment by tuarua** [comment] 2019-10-22 11:31
This is because you are using a HiDPI monitor and not including the relevant tag in the app xml
as per the **example included with the repo.**

https://github.com/tuarua/WebViewANE/blob/fb80e726a79ac4f0ae098619c04ec99d6d9da795/example-desktop-flex/src/WebViewExampleFlex-app.xml#L13

**Closed by tuarua** 2019-10-22 11:31 UTC
Labels: support
